<?php

declare(strict_types=1);

namespace CodeLandQuiz\Model;

enum AuditAction: string
{
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGOUT = 'LOGOUT';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';

    case TEACHER_CREATED = 'TEACHER_CREATED';
    case TEACHER_UPDATED = 'TEACHER_UPDATED';
    case TEACHER_ACTIVATED = 'TEACHER_ACTIVATED';
    case TEACHER_DEACTIVATED = 'TEACHER_DEACTIVATED';
    case TEACHER_PASSWORD_RESET = 'TEACHER_PASSWORD_RESET';

    case STUDENT_CREATED = 'STUDENT_CREATED';
    case STUDENT_UPDATED = 'STUDENT_UPDATED';
    case STUDENT_ACTIVATED = 'STUDENT_ACTIVATED';
    case STUDENT_DEACTIVATED = 'STUDENT_DEACTIVATED';

    case QUIZ_CREATED = 'QUIZ_CREATED';
    case QUIZ_UPDATED = 'QUIZ_UPDATED';
    case QUIZ_DELETED = 'QUIZ_DELETED';

    case QUESTION_CREATED = 'QUESTION_CREATED';
    case QUESTION_UPDATED = 'QUESTION_UPDATED';
    case QUESTION_DELETED = 'QUESTION_DELETED';
    case QUESTIONS_REORDERED = 'QUESTIONS_REORDERED';

    case QUIZ_ACTIVATED = 'QUIZ_ACTIVATED';
    case QUIZ_DEACTIVATED = 'QUIZ_DEACTIVATED';

    case TOPIC_CREATED = 'TOPIC_CREATED';
    case TOPIC_UPDATED = 'TOPIC_UPDATED';
    case TOPIC_DELETED = 'TOPIC_DELETED';

    case SESSION_STARTED = 'SESSION_STARTED';
    case SESSION_FINISHED = 'SESSION_FINISHED';
    case QUIZ_SESSION_CREATED = 'QUIZ_SESSION_CREATED';
    case QUIZ_SESSION_STARTED = 'QUIZ_SESSION_STARTED';
    case QUIZ_SESSION_QUESTION_CLOSED = 'QUIZ_SESSION_QUESTION_CLOSED';
}
