<?php

declare(strict_types=1);

namespace CodeLandQuiz\Model;

enum AuditAction: string
{
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGOUT = 'LOGOUT';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';

    case TEACHER_CREATED = 'TEACHER_CREATED';
    case TEACHER_UPDATED = 'TEACHER_UPDATED';
    case TEACHER_ACTIVATED = 'TEACHER_ACTIVATED';
    case TEACHER_DEACTIVATED = 'TEACHER_DEACTIVATED';
    case TEACHER_PASSWORD_RESET = 'TEACHER_PASSWORD_RESET';

    case QUIZ_CREATED = 'QUIZ_CREATED';
    case QUIZ_UPDATED = 'QUIZ_UPDATED';
    case QUIZ_DELETED = 'QUIZ_DELETED';

    case TOPIC_CREATED = 'TOPIC_CREATED';
    case TOPIC_UPDATED = 'TOPIC_UPDATED';
    case TOPIC_DELETED = 'TOPIC_DELETED';

    case SESSION_STARTED = 'SESSION_STARTED';
    case SESSION_FINISHED = 'SESSION_FINISHED';
}
